version: '3.8'
services:
  messenger-db:
    container_name: messenger
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'messenger-db'
      MYSQL_ROOT_USER: 'user'
      MYSQL_USER_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - '3310:3306'
    expose:
      - '3310'
    volumes:
      - messenger-db:/var/lib/mysql

volumes:
  messenger-db: